export const DEVICELIST_FETCH_START = "DEVICELIST_FETCH_START";
export const DEVICELIST_FETCH_SUCCESS = "DEVICELIST_FETCH_SUCCESS";
export const DEVICELIST_FETCH_FAIL = "DEVICELIST_FETCH_FAIL";
export const DEVICELIST_RESET = "DEVICELIST_RESET";

export const DEVICESTATE_UPDATE = "DEVICESTATE_UPDATE";
export const DEVICESTATE_UPDATE_FAIL = "DEVICESTATE_UPDATE_FAIL";

export const DEVICE_APPLIANCE_LOGS_START = "DEVICE_APPLIANCE_LOGS_START";
export const DEVICE_APPLIANCE_LOGS_SUCCESS = "DEVICE_APPLIANCE_LOGS_SUCCESS";
export const DEVICE_APPLIANCE_LOGS_FAIL = "DEVICE_APPLIANCE_LOGS_FAIL";
