export const DEVICELIST_FETCH_START = "DEVICELIST_FETCH_START";
export const DEVICELIST_FETCH_SUCCESS = "DEVICELIST_FETCH_SUCCESS";
export const DEVICELIST_FETCH_FAIL = "DEVICELIST_FETCH_FAIL";

export const DEVICESTATE_UPDATE_START = "DEVICESTATE_UPDATE_START";
export const DEVICESTATE_UPDATE_SUCCESS = "DEVICESTATE_UPDATE_SUCCESS";
export const DEVICESTATE_UPDATE_FAIL = "DEVICESTATE_UPDATE_FAIL";