export const USER_AUTH_START = "USER_AUTH_START";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAIL = "USER_AUTH_FAIL";
export const RESET = "RESET";
export const LOGOUT = "LOGOUT";

export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const UNVERIFIED_USERLIST_FETCH_START =
  "UNVERIFIED_USERLIST_FETCH_START";
export const UNVERIFIED_USERLIST_FETCH_SUCCESS =
  "UNVERIFIED_USERLIST_FETCH_SUCCESS";
export const UNVERIFIED_USERLIST_FETCH_FAIL = "UNVERIFIED_USERLIST_FETCH_FAIL";

export const UNVERIFIED_USER_UPDATE = "UNVERIFIED_USER_UPDATE";

export const USER_DELETE_START = "USER_DELETE_START";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";

export const USER_EDIT_START = "USER_EDIT_START";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAIL = "USER_EDIT_FAIL";
export const USER_EDIT_RESET = "USER_EDIT_RESET";

export const USER_FETCH_START = "USER_FETCH_START";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAIL = "USER_FETCH_FAIL";
export const USER_FETCH_RESET = "USER_FETCH_RESET";

export const SET_CURRENT_USER = "CURRENT_USER_INFO";
export const USER_AUTHORIZE = "USER_AUTHORIZE";
export const USER_INFO_RESET = "USER_INFO_RESET";
export const IS_ADMIN = "IS_ADMIN";
